# Generated by Django 5.1.2 on 2024-10-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Jacob', max_length=20)),
                ('email', models.EmailField(default='email@example.com', max_length=254)),
            ],
        ),
    ]
